### Recuperar todos los libros
GET http://localhost:3000/books/

### Recuperar información sobre un libro y sus autores
GET http://localhost:3000/books/authors/8


### Recuperar información sobre libros que se hayan publicado despues del parametro enviado
GET http://localhost:3000/books/publicationYear/1500




### Recuperar todos los usuario del sistema
GET http://localhost:3000/users/


