###--------------------------------------------------
# AQUÍ INICIAN LOS ENDPOINTS DEL INICIO DE SESIÓN

### Login
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
  "userEmail": "royer.b@mail.com",
  "userPassword": "passRoye"
}

###---------------------------------------------
# AQUÍ INICIAN LOS ENDPOINTS DE SOBRE EL RECURSO DE LIBROS

### Recuperar todos los libros
GET http://localhost:3000/books/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJyb3llci5iQG1haWwuY29tIiwiaWF0IjoxNzc2NzA4MDM5LCJleHAiOjE3NzY3MDk4Mzl9.soHMik29XwGYWrS7zCZsHazyUf52AOgFjkCkCXMGuTY

### Recuperar el total de Autores registrados
GET http://localhost:3000/books/totalAuthors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJyb3llci5iQG1haWwuY29tIiwiaWF0IjoxNzc2NzEzMjMzLCJleHAiOjE3NzY3MTY4MzN9.fZgrmc8vsD0UV5tIDNMaXooCtkZFk_mRiZvR4FEF9Ik

### Recuperar todos los Autores paginados
GET http://localhost:3000/books/authors/10/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJyb3llci5iQG1haWwuY29tIiwiaWF0IjoxNzc2NzEzMjMzLCJleHAiOjE3NzY3MTY4MzN9.fZgrmc8vsD0UV5tIDNMaXooCtkZFk_mRiZvR4FEF9Ik

### Recuperar información sobre un libro y sus autores
GET http://localhost:3000/books/authors/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJyb3llci5iQG1haWwuY29tIiwiaWF0IjoxNzc2MjgzMzAwLCJleHAiOjE3NzYyODM2MDB9.fjAwNTYpc6Cf4GqZv2U3EahQs_HswqYEAG8N6snJkIM

### Recuperar información sobre libros que se hayan publicado despues del parametro enviado
GET http://localhost:3000/books/publicationYear/1500
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJyb3llci5iQG1haWwuY29tIiwiaWF0IjoxNzc2MjgzMzAwLCJleHAiOjE3NzYyODM2MDB9.fjAwNTYpc6Cf4GqZv2U3EahQs_HswqYEAG8N6snJkIM

### Crear un nuevo libro
POST http://localhost:3000/books/
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhbmEubG9wZXpAbWFpbC5jb20iLCJpYXQiOjE3NzYxOTQ0MzgsImV4cCI6MTc3NjE5ODAzOH0.x36a3611Lt0OA-YhIJZgWTvjQx6mpq6XgpmDcGTBNWA
Content-Type: application/json

{
  "title": "The shining",
  "publicationYear": "1977"
}

### ---------------------------------------
# AQUÍ INICIAN LOS ENDPOINTS DE SOBRE EL RECURSO DE USUARIOS

### Recuperar todos los usuario del sistema
GET http://localhost:3000/users/

### Crear un nuevo usuario
POST http://localhost:3000/users/
Content-Type: application/json

{
  "userName": "Bob Esponja",
  "idRole": 1,
  "userEmail": "bob.esponja@mail.com",
  "userPassword": "passB"
}

### Actualizar la contraseña de un usuario
PATCH http://localhost:3000/users/
Content-Type: application/json

{
  "userEmail": "bob.esponja@mail.com",
  "userNewPassword": "passBo"
}

